name: Build Docs
on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/docs.yml"
      - "docs/**"
jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm run ci:docs
      - name: Build docs
        run: npm run docs:build
      - name: Upload docs to COS
        run: node scripts/upload-docs-to-cos.js
