name: Build Docs
on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/docs.yml"
      - "docs/**"
jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm run ci:docs
      - name: Build docs
        run: npm run docs:build
      - name: Upload docs to COS
        run: node scripts/upload-docs-to-cos.js
        env:
          COS_SECRET_ID: ${{ secrets.COS_SECRET_ID }}
          COS_SECRET_KEY: ${{ secrets.COS_SECRET_KEY }}
          COS_DOMAIN: ${{ secrets.COS_DOMAIN }}
          COS_BUCKET: ${{ secrets.COS_BUCKET }}
          COS_REGION: ${{ secrets.COS_REGION }}
